
name: Build and release Apple Silicon Ripes version

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Ripes on Apple Silicon
    permissions:
      contents: write
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: echo '1' | ./build.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Find tag
        id: version
        run: |
          echo VERSION=$(gh release list --repo mortbopet/Ripes --json tagName -q '.[1].tagName' --order desc --limit 2) >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Zip
        run: zip -r ripes-v2.2.6-mac-arm.zip ~/ripes-ntnu
        env:
          VERSION: ${{ steps.version.outputs.VERSION }}

      - name: Publish Release
        run: gh release create $VERSION ripes-$VERSION-mac-arm.zip
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.version.outputs.VERSION }}
    
